// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZ3Kh7edGr8Tj739LXLhbgPnFAjRzfdM',
    appId: '1:467455339293:web:34c2aca519acf9cd308ff4',
    messagingSenderId: '467455339293',
    projectId: 'notes-app-2304f',
    authDomain: 'notes-app-2304f.firebaseapp.com',
    storageBucket: 'notes-app-2304f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabb9HhJKFzFtPcahNCajoD9gJjfX5W6c',
    appId: '1:467455339293:android:99d77a9fe7cc1737308ff4',
    messagingSenderId: '467455339293',
    projectId: 'notes-app-2304f',
    storageBucket: 'notes-app-2304f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LAdH1o_uq5G6AHBu8ngohdOC9V-V2tI',
    appId: '1:467455339293:ios:929cb7c995598106308ff4',
    messagingSenderId: '467455339293',
    projectId: 'notes-app-2304f',
    storageBucket: 'notes-app-2304f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9LAdH1o_uq5G6AHBu8ngohdOC9V-V2tI',
    appId: '1:467455339293:ios:929cb7c995598106308ff4',
    messagingSenderId: '467455339293',
    projectId: 'notes-app-2304f',
    storageBucket: 'notes-app-2304f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbZ3Kh7edGr8Tj739LXLhbgPnFAjRzfdM',
    appId: '1:467455339293:web:9b5df1786e0ba562308ff4',
    messagingSenderId: '467455339293',
    projectId: 'notes-app-2304f',
    authDomain: 'notes-app-2304f.firebaseapp.com',
    storageBucket: 'notes-app-2304f.appspot.com',
  );

}